version: "3.9"

services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    expose:
      - "3000"

  caddy:
    image: caddy:latest
    container_name: caddy_server
    ports:
      - "8080:80"
      - "4430:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs

volumes:
  caddy_data:
  caddy_config:
